-- migrate:up
CREATE TABLE color_palette (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  color1 VARCHAR(10) NULL DEFAULT '#FF96A8',
  color2 VARCHAR(10) NULL DEFAULT '#FDB844',
  color3 VARCHAR(10) NULL DEFAULT '#2DD4BF',
  color4 VARCHAR(10) NULL DEFAULT '#547AFF',
  color5 VARCHAR(10) NULL DEFAULT '#AF71FF',
  color6 VARCHAR(10) NULL DEFAULT '#787676'
  );

-- migrate:down
DROP TABLE color_palette;